return {
  pde = {
    ai = false,
    angular = false,
    cpp = false,
    csharp = true,
    docker = true,
    elixir = false,
    flutter = false,
    go = true,
    html = true,
    java = false,
    json = true,
    julia = false,
    jupyter = false,
    kotlin = false,
    lua = true,
    python = false,
    r = false,
    react = false,
    ruby = false,
    rust = true,
    scala = false,
    solidity = false,
    svelte = true,
    tailwind = true,
    terraform = false,
    typescript = true,
    vuejs = true,
  },
}
